<?php

namespace Database\Seeders;

use App\Models\Ingredient;
use Illuminate\Database\Seeder;
use Illuminate\Support\Collection;

class IngredientSeeder extends Seeder
{
    public function run(): void
    {
        $ingredients = [
            'White pepper',
            'Garlic pepper',
            'cayene Pepper',
            'Chilli Pepper',
            'Black Pepper',
            'Chicken seasoning',
            'Paprika',
            'Cinamone',
            'Comander',
            'Cmono MMoluo',
            'Curry masala',
            'fish Seaoning',
            'pepper soup seasoning',
            'whole oregano',
            'parsley Leaf',
            'nsala spices',
            'Pink salt',
            'Madras Curry',
            'Baking soda',
            'vanilla Falvours',
            'Brown sugar',
            'fennel Seeds',
            'baked Beans',
            'PLum Tomatoes',
            'Tomato Paste',
            'Yeast',
            'Instant Milk2',
            'Lemon Juice',
            'Flour',
            'Sugar',
            'cummi seed',
            'Seasame Seed',
            'Taglatelle',
            'Honey',
            'MUSTARD',
            'Sweet potatoe',
            'Irish Potato',
            'Yam',
            'Fresh cinger',
            'Rosemary',
            'Crayfish',
            'Fresh Garlic',
            'Wuda',
            'Icing Sugar',
            'Fresh tomatoe',
            'Item Name',
            'Fresh pepper',
            'Eggs',
            'Jubi Butter',
            'Moore Butter',
            'Rhoda Butter',
            'Bale pepper',
            'cucmber',
            'Corn Beef',
            'red chilli',
            'Stock fish',
            'Dry Fish',
            'Fresh fries',
            'president butter',
            'cheddu chilli',
            'slice cuedda',
            'yoghut Unsweatened',
            'chocolate Bar',
            'Salmon Fillet',
            'Sausage',
            'Satix',
            'White fish',
            'Jam',
            'Tortilla Bread',
            'Condense Milk',
            'Crab Cruster',
            'calamari',
            'Whole Chicken',
            'Mix vegetable',
            'White Springs',
            'Mix Sea Food',
            'Croaker Fillet',
            'Tilapia',
            'baby shrimps',
            'jombo crak tiger',
            'big shrimps',
            'wheat',
            'semo',
            'Cabbage',
            'cauli flower',
            'brocolli',
            'Spring',
            'Lettuce',
            'Item Name',
            'Spring onion',
            'Ice beg Lettuce',
            'Parsely',
            'Curry tomato',
            'Maggie Knorr',
            'rice',
            'batmatise Rice',
            'salt',
            'Slice bread',
            'Baking pepper',
            'Aluminium Foil',
            'clear Fin',
            'Takeaway Pack',
            'shawama sauce',
            'power oil',
            'palm oil',
            'white vingear',
            'bama',
            'Tomaoto Ketchup',
            'Annan Pineapple',
            'Seaseme Oil',
            'Olive Oil',
            'Chilli sauce',
            'Light soy souce',
            'SUCCI and SAShimi',
            'Dark soy souce',
            'Sweet chilli sause',
            'Fish Sause',
            'Prenium oyster saucee',
            'Lasane Tomato',
            'Mini gherkins',
            'Roasted Garlic Parmesa sauce',
            'Black Olive oil 2',
            'sun dry tomato',
            'Classsic pasto',
            'Mixed pickle',
            'corn flour',
            'Kings Oil',
            'Ducrus Curry',
            'Spaghetti',
            'yam',
            'Beef',
            'Onion',
            'Chicken Breast',
            'Windolene',
            'Carrot',
            'Bell Pepper',
            'Semo Nylon',
            'Cauli Flower',
            'Brocolli',
            'Green Bean',
            'Green Leaf',
            'Shoko',
            'Assorted Meat',
            'Sweet Corn',
            'Panla Fish',
            'Iru',
            'Tatashe',
            'Ponmo',
            'Bama Mayonise',
            'Ede Thickner',
            'Wozzarella Cheese',
            'Fresh Shombo',
            'Oha Leaf',
            'thyme',
            'Ugu Leaf',
            'Egusi ',
            'Ogbono',
            'Banga',
            'Ogu Leaf',
            'Uzuza Leaf',
            'Ogiri',
            'Semovita',
            'Long grain Rice',
            'Yellow Pepper',
            'Splenda Bulgarian',
            'lamothe parrot original',
            'Expression White Wine',
            'President Original',
            'Minced Meat',
            'Fietsa White Fish',
            'Stute Juice Drink',
            'Brocolli',
            'spinash',
            'Sharwarma Wrap',
            'MOi MOi Cup',
        ];

        Collection::make($ingredients)
            ->map(fn (string $ingredient): string => trim($ingredient))
            ->filter(fn (string $ingredient): bool => $ingredient !== '' && strcasecmp($ingredient, 'Item Name') !== 0)
            ->unique(fn (string $ingredient): string => mb_strtolower($ingredient))
            ->values()
            ->each(function (string $name): void {
                Ingredient::query()->firstOrCreate(
                    ['name' => $name],
                    [
                        'unit' => 'pcs',
                        'current_stock' => 0,
                        'min_stock_alert_level' => 10,
                    ]
                );
            });
    }
}
